export const speakers = [
  {
    name: '정충일',
    title: '프로젝트 기획부터 배포까지',
    univ: '수원대',
    subTitle: '주최자',
    sessionNumber: 1,
    time: '13:00 - 13:20',
    imageUrl: '/images/tooooo1_speaker.png',
    github: 'https://github.com/tooooo1',
  },
  {
    name: '김영진',
    title: 'To. 부트캠프를 준비하는 분들에게',
    univ: '아주대',
    subTitle: 'Undefined',
    sessionNumber: 2,
    time: '13:20 - 13:40',
    imageUrl: '/images/jin-Pro_speaker.png',
    github: 'https://github.com/jin-Pro',
  },
  {
    name: '임광열',
    title: '나의 첫 번째 취업, 그리고 첫 번째 이직',
    univ: '폴리텍대',
    subTitle: '채널톡',
    sessionNumber: 3,
    time: '13:40 - 14:00',
    imageUrl: '/images/GwangYeol-Im_speaker.png',
    github: 'https://github.com/GwangYeol-Im',
  },
  {
    name: '차재명',
    title: 'Svelte, 들어보셨나요?',
    univ: '아주대',
    subTitle: 'KAKAO',
    sessionNumber: 4,
    time: '14:00 - 14:20',
    imageUrl: '/images/Coreight98_speaker.png',
    github: 'https://github.com/Coreight98',
  },
  {
    name: '황정민',
    title: '비전공자 FE 입문 이야기',
    univ: '국민대',
    subTitle: '우테코 4기',
    sessionNumber: 5,
    time: '14:20 - 14:40',
    imageUrl: '/images/hwangstar156_speaker.png',
    github: 'https://github.com/hwangstar156',
  },
  {
    name: '박은식',
    title: 'UX',
    univ: '충남대',
    subTitle: 'TOSS',
    sessionNumber: 6,
    time: '14:40 - 15:00',
    imageUrl: '/images/qkrdmstlr3_speaker.png',
    github: 'https://github.com/qkrdmstlr3',
  },
];
