export const speakers = [
  {
    name: '정충일',
    title: '프로젝트 기획부터 배포까지',
    univ: '수원대',
    subTitle: '주최자',
    sessionNumber: 1,
    time: '13:00 - 13:15',
    imageUrl: '/images/tooooo1_speaker.png',
    github: 'https://github.com/tooooo1',
  },
  {
    name: '스피커2',
    title: '제목이 들어가는 곳',
    univ: '대학교',
    subTitle: '타이틀',
    sessionNumber: 2,
    time: '13:15 - 13:30',
    imageUrl: '/images/speaker.png',
    github: 'https://github.com/tooooo1',
  },
  {
    name: '스피커3',
    title: '제목이 들어가는 곳',
    univ: '대학교',
    subTitle: '타이틀',
    sessionNumber: 3,
    time: '13:30 - 13:45',
    imageUrl: '/images/speaker.png',
    github: 'https://github.com/tooooo1',
  },
  {
    name: '스피커4',
    title: '제목이 들어가는 곳',
    univ: '대학교',
    subTitle: '타이틀',
    sessionNumber: 4,
    time: '13:45 - 14:00',
    imageUrl: '/images/speaker.png',
    github: 'https://github.com/tooooo1',
  },
  {
    name: '스피커5',
    title: '제목이 들어가는 곳',
    univ: '대학교',
    subTitle: '타이틀',
    sessionNumber: 5,
    time: '14:00 - 14:15',
    imageUrl: '/images/speaker.png',
    github: 'https://github.com/tooooo1',
  },
  {
    name: '스피커6',
    title: '제목이 들어가는 곳',
    univ: '대학교',
    subTitle: '타이틀',
    sessionNumber: 6,
    time: '14:15 - 14:30',
    imageUrl: '/images/speaker.png',
    github: 'https://github.com/tooooo1',
  },
];
